development:
  secret_key_base: 8f1384c6a3dafe82ebb2ce920ba0c161aa8301ef34caa23ace303656de946f0cf29348fa42050d40fa05b92f2f04226cb4e8f14c8b7ea9203c06a5cc6cafa4c3
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_email_address: <%= ENV["SMTP_EMAIL_ADDRESS"] %>
  smtp_email_reciever: <%= ENV["SMTP_EMAIL_RECIEVER"] %>

  user_email: <%= ENV["USER_EMAIL"] %>
  user_password: <%= ENV["USER_PASSWORD"] %>

test:
  secret_key_base: 3d21724cf5f5c67f899ffa3d56b923b61722f0ae73cc82f6f21e5d4e243a18a65498c4b182cdca024fb514bfdf9e67bdccad04087af75ddef2955cb03cabed06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_email_address: <%= ENV["SMTP_EMAIL_ADDRESS"] %>
  smtp_email_reciever: <%= ENV["SMTP_EMAIL_RECIEVER"] %>

  user_email: <%= ENV["USER_EMAIL"] %>
  user_password: <%= ENV["USER_PASSWORD"] %>